### ISSUE TITLE
Problem with Scrypt VScode extension on Windows

### ISSUE THREAD

**Issue by bvqbao** [sCrypt-Inc/compiler_dist#3]
Hi,

This error shows up whenever I start my VSCode (with sCrypt extension installed) on Windows:

![image](https://user-images.githubusercontent.com/4357219/137620248-e11c0dc8-558a-4af6-b5c1-ba34cc399e51.png)

It seems that it doesn't like the fact that my user folder name contains spaces.

Any suggestion? (beside changing my user folder name, which is very hard to do it right on Windows).

Thanks,

**Comment by zhfnjust** [comment]
laster version fix this.

**Comment by zhfnjust** [comment]
close due to not active
